version: "3"
services:
        login-app:
            container_name: login-app
            image: my-nodejs-mongodb-app
            restart: always
            build: .
            ports:
              - "7500:7500"
            links:
              - mongo
        mongo:
          image: mongo
          restart: always
          environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

        mongo-express:
          image: mongo-express
          restart: always
          ports:
            - 8081:8081
          environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/